 "use client";
import {useState} from "react";
import {Home,MessageCircle,Plus,ChartNoAxesColumn,CalendarDays,ShoppingCart,Car,House,Cat} from "lucide-react";
type E={id:number;title:string;cat:string;who:string;amount:number};
const fmt=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const budgets={Casa:2500,Carro:3000,Assinaturas:500,Pets:650,Alimentação:1400,Transporte:800,Lazer:700,Pessoal:1000};
const start:E[]=[["Condomínio","Casa","Casal",525],["Garagem","Casa","Casal",300],["Parcela do carro","Carro","Casal",1680],["Seguro","Carro","Casal",500],["Internet","Casa","Casal",100],["Luz","Casa","Casal",165],["FIES","Pessoal","Bruna",553.2],["Ração","Pets","Casal",80],["Areia","Pets","Casal",100],["Plano de saúde pets","Pets","Casal",385]].map((x,i)=>({id:i,title:x[0] as string,cat:x[1] as string,who:x[2] as string,amount:x[3] as number}));
export default function Page(){
 const [es,setEs]=useState(start),[tab,setTab]=useState("home"),[text,setText]=useState(""),[modal,setModal]=useState(false),[toast,setToast]=useState("");
 const total=es.reduce((a,e)=>a+e.amount,0),available=13000-total;
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2000)};
 const send=()=>{const m=text.match(/(\d+[\d\.,]*)/);if(!m){notify("Ex.: gastei 50 no mercado");return}const amount=Number(m[1].replaceAll(".","").replace(",","."));let cat="Outros";if(/mercado|comida/i.test(text))cat="Alimentação";if(/gasolina|posto/i.test(text))cat="Transporte";if(/shopping|lazer/i.test(text))cat="Lazer";setEs(x=>[{id:Date.now(),title:text,cat,who:/matheus/i.test(text)?"Matheus":"Bruna",amount},...x]);setText("");notify("Gasto registrado 💚")};
 return <div className="app">{toast&&<div className="toast">{toast}</div>}
 <header className="top"><div><div className="brand">Bru<span>Math</span> 💚</div><div className="sub">Finanças de Bruna & Matheus</div></div><div className="avatar">BM</div></header>
 {tab==="home"&&<><section className="hero"><small>Disponível em agosto</small><div className="amount">{fmt(available)}</div><div className="progress"><i style={{width:`${Math.min(100,total/13000*100)}%`}}/></div><div className="row"><span>Usado {fmt(total)}</span><span>Renda {fmt(13000)}</span></div></section>
 <div className="cards"><div className="card"><div className="label">Limite Matheus</div><div className="value">{fmt(Math.max(0,350-es.filter(e=>e.who==="Matheus").reduce((a,e)=>a+e.amount,0)))}</div></div><div className="card"><div className="label">Parcelas</div><div className="value">8 ativas</div></div></div>
 <div className="section"><h2>Assistente</h2><span className="sub">online</span></div><div className="chat"><div className="bubble">Oi! 💚 Pode falar normalmente comigo. Ex.: <b>“gastei 85 no mercado”</b>.</div><div className="quick"><button onClick={()=>setText("quanto temos?")}>Quanto temos?</button><button onClick={()=>setText("resumo")}>Resumo</button><button onClick={()=>setText("parcelas")}>Parcelas</button></div><div className="inputrow"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ex.: gastei 50 no mercado"/><button className="send" onClick={send}>Enviar</button></div></div>
 <div className="section"><h2>Últimos gastos</h2><span className="sub">Agosto</span></div><div className="list">{es.slice(0,7).map(e=><div className="expense" key={e.id}><div className="ico">{e.cat==="Carro"?<Car size={18}/>:e.cat==="Pets"?<Cat size={18}/>:e.cat==="Casa"?<House size={18}/>:<ShoppingCart size={18}/>}</div><main><b>{e.title}</b><span>{e.cat} · {e.who}</span></main><strong>{fmt(e.amount)}</strong></div>)}</div></>}
 {tab==="stats"&&<><div className="section"><h2>Limites por categoria</h2></div><div className="list">{Object.entries(budgets).map(([c,b])=>{const u=es.filter(e=>e.cat===c).reduce((a,e)=>a+e.amount,0);return <div key={c} style={{padding:"12px 0"}}><div style={{display:"flex",justifyContent:"space-between",fontSize:12}}><b>{c}</b><span>{fmt(u)} / {fmt(b)}</span></div><div className="progress" style={{background:"#e8ece8",marginTop:7}}><i style={{width:`${Math.min(100,u/b*100)}%`,background:"#17221c"}}/></div></div>})}</div></>}
 {tab==="future"&&<><div className="section"><h2>Futuro</h2></div><div className="list"><div className="expense"><div className="ico"><CalendarDays/></div><main><b>Parcela do apartamento</b><span>A partir de setembro</span></main><strong>{fmt(1300)}</strong></div><div className="expense"><div className="ico">💳</div><main><b>Parcelas identificadas</b><span>Globo, Rei do Óleo, Hocks, Lojão, perfumes e outras</span></main><strong>8</strong></div></div></>}
 {tab==="chat"&&<><div className="section"><h2>BruMath</h2></div><div className="chat"><div className="bubble">💚 Pergunte qualquer coisa sobre o orçamento.</div><div className="inputrow"><input value={text} onChange={e=>setText(e.target.value)} placeholder="O que você quer saber?"/><button className="send" onClick={send}>Enviar</button></div></div></>}
 <button className="fab" onClick={()=>setModal(true)}><Plus/></button><nav className="bottom"><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}><Home size={19}/>Início</button><button className={tab==="chat"?"active":""} onClick={()=>setTab("chat")}><MessageCircle size={19}/>Assistente</button><button className={tab==="stats"?"active":""} onClick={()=>setTab("stats")}><ChartNoAxesColumn size={19}/>Categorias</button><button className={tab==="future"?"active":""} onClick={()=>setTab("future")}><CalendarDays size={19}/>Futuro</button></nav>
 {modal&&<div className="modal" onClick={()=>setModal(false)}><form className="sheet" onClick={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setEs(x=>[{id:Date.now(),title:String(f.get("title")),cat:String(f.get("cat")),who:String(f.get("who")),amount:Number(f.get("amount"))},...x]);setModal(false);notify("Gasto adicionado 💚")}}><h2>Novo gasto</h2><div className="field"><label>O que foi?</label><input name="title" required placeholder="Mercado"/></div><div className="field"><label>Valor</label><input name="amount" type="number" step="0.01" required/></div><div className="field"><label>Categoria</label><select name="cat">{Object.keys(budgets).map(c=><option key={c}>{c}</option>)}<option>Outros</option></select></div><div className="field"><label>Quem?</label><select name="who"><option>Bruna</option><option>Matheus</option><option>Casal</option></select></div><button className="primary">Salvar</button><button type="button" className="cancel" onClick={()=>setModal(false)}>Cancelar</button></form></div>}</div>
}