import type { Expense, Installment } from "../../lib/app/AppTypes";

export const DEFAULT_BUDGETS: Record<string, number> = {
  Casa: 2500,
  Carro: 3000,
  Assinaturas: 500,
  Pets: 650,
  Alimentação: 1400,
  Transporte: 800,
  Lazer: 700,
  Pessoal: 1000,
  Trabalho: 300,
  Outros: 500,
};

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 1,
    title: "Condomínio",
    cat: "Casa",
    who: "Casal",
    amount: 525,
    date: "2026-08-01",
  },
  {
    id: 2,
    title: "Garagem",
    cat: "Casa",
    who: "Casal",
    amount: 300,
    date: "2026-08-02",
  },
  {
    id: 3,
    title: "Parcela do carro",
    cat: "Carro",
    who: "Casal",
    amount: 1680,
    date: "2026-08-03",
  },
  {
    id: 4,
    title: "Seguro",
    cat: "Carro",
    who: "Casal",
    amount: 500,
    date: "2026-08-04",
  },
  {
    id: 5,
    title: "Internet",
    cat: "Casa",
    who: "Casal",
    amount: 100,
    date: "2026-08-05",
  },
  {
    id: 6,
    title: "Luz",
    cat: "Casa",
    who: "Casal",
    amount: 165,
    date: "2026-08-06",
  },
  {
    id: 7,
    title: "FIES",
    cat: "Pessoal",
    who: "Bruna",
    amount: 553.2,
    date: "2026-08-07",
  },
  {
    id: 8,
    title: "Mercado",
    cat: "Alimentação",
    who: "Bruna",
    amount: 50,
    date: "2026-08-08",
  },
  {
    id: 9,
    title: "Petisco gatos",
    cat: "Pets",
    who: "Casal",
    amount: 10,
    date: "2026-08-09",
  },
];

export const INITIAL_INSTALLMENTS: Installment[] = [
  {
    id: 1,
    title: "Parcela do carro",
    category: "Carro",
    who: "Casal",
    amount: 1680,
    totalInstallments: 48,
    paidInstallments: 8,
    nextDue: "2026-09-10",
  },
  {
    id: 2,
    title: "Parcela do apartamento",
    category: "Casa",
    who: "Casal",
    amount: 1300,
    totalInstallments: 120,
    paidInstallments: 18,
    nextDue: "2026-09-01",
  },
  {
    id: 3,
    title: "Globo",
    category: "Assinaturas",
    who: "Casal",
    amount: 24.9,
    totalInstallments: 12,
    paidInstallments: 7,
    nextDue: "2026-09-10",
  },
  {
    id: 4,
    title: "Rei do Óleo",
    category: "Carro",
    who: "Casal",
    amount: 210,
    totalInstallments: 6,
    paidInstallments: 2,
    nextDue: "2026-09-12",
  },
  {
    id: 5,
    title: "Hocks",
    category: "Pessoal",
    who: "Bruna",
    amount: 89.9,
    totalInstallments: 8,
    paidInstallments: 3,
    nextDue: "2026-09-15",
  },
  {
    id: 6,
    title: "Lojão",
    category: "Pessoal",
    who: "Matheus",
    amount: 150,
    totalInstallments: 10,
    paidInstallments: 4,
    nextDue: "2026-09-18",
  },
];
